name: 'Transfer Issue & Create Stub'
description: 'A GitHub Action for transferring issues between github repos with the ability to create a stub issue in the original repo.'
author: 'John Ouellet'
inputs:
  destination_repo:
    description: 'The destination repo.'
    required: false
  github-token:
    description: 'The GitHub token used to create an authenticated client.'
    default: ${{ github.token }}
    required: false
  create_stub:
    description: 'Create a stub issue with title and description in original repo.'
    default: true
    required: false
  labels_file_path:
    description: 'Create a label if it does not exist in the trasnferred repo and tag the transferred issue.'
    required: false
  map_repo_labels_file_path:
    description: 'Maps the triggering label to a file keyed `label:destination_repo`. If the label is found, it will transfer the issue to that repo. If not, it will exit the process and not tranfer any issue'
    required: false
outputs:
  transferred_issue_number:
    description: 'The issue number of the transferred issue'
  transferred_issue_url:
    description: 'The issue url of the transferred issue'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: "green"
  icon: "arrow-right-circle"  
